export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';

//Test modals
export const OPEN_MODAL = 'OPEN_MODAL';
